services:
  backend:
    build: ./backend
    container_name: pref-rh-backend
    entrypoint: ["/app/entrypoint.sh"]  # Atualizado para o caminho correto dentro do container
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://rhuser:rhpass@db:5432/rhdb
  
  frontend:
    image: php:8.2-apache
    container_name: pref-rh-frontend
    volumes:
      - ./frontend:/var/www/html
      - ./frontend/apache-custom.conf:/etc/apache2/conf-available/custom.conf
    ports:
      - "8080:80"
    depends_on:
      - db
    command: bash -c "a2enconf custom && service apache2 reload && apache2-foreground"

  db:
    image: postgres:15
    container_name: pref-rh-db
    restart: always
    environment:
      POSTGRES_DB: rhdb
      POSTGRES_USER: rhuser
      POSTGRES_PASSWORD: rhpass
      POSTGRES_INITDB_ARGS: "--auth-local=md5 --auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: pref-rh-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  dbdata: